#!/usr/bin/env bash
# 07-backups.sh — Setup backup scripts and cron job
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/lib.sh"

require_root
load_env

BACKUP_RETENTION_DAYS="${BACKUP_RETENTION_DAYS:-7}"
BACKUP_CRON_TIME="${BACKUP_CRON_TIME:-0 3 * * *}"

section "Backup Setup"

BACKUP_DIR="/opt/backups"
BACKUP_DATA_DIR="${BACKUP_DIR}/data"
BACKUP_SCRIPT="${BACKUP_DIR}/run-backup.sh"

# ---------------------------------------------------------------------------
# Create backup directories
# ---------------------------------------------------------------------------
log_info "Creating backup directories..."
run mkdir -p "$BACKUP_DIR" "$BACKUP_DATA_DIR"

# ---------------------------------------------------------------------------
# Generate backup script
# ---------------------------------------------------------------------------
log_info "Generating backup script at ${BACKUP_SCRIPT}..."

if [[ "$DRY_RUN" != "true" ]]; then
    cat > "$BACKUP_SCRIPT" <<'BACKUPSCRIPT'
#!/usr/bin/env bash
# run-backup.sh — Automated backup of server configs, Docker volumes, and Traefik data
# Generated by deployment-ready-ubuntu/scripts/07-backups.sh
set -euo pipefail

BACKUP_DIR="/opt/backups/data"
RETENTION_DAYS="${BACKUP_RETENTION_DAYS:-7}"
TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
ARCHIVE="${BACKUP_DIR}/backup-${TIMESTAMP}"

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"; }

log "Starting backup..."

# Create temp staging directory
STAGING=$(mktemp -d)
trap 'rm -rf "$STAGING"' EXIT

# --- 1. System configs ---
log "Backing up system configs..."
mkdir -p "${STAGING}/etc"
cp -a /etc/ssh/sshd_config "${STAGING}/etc/" 2>/dev/null || true
cp -a /etc/ssh/sshd_config.d "${STAGING}/etc/" 2>/dev/null || true
cp -a /etc/ufw "${STAGING}/etc/" 2>/dev/null || true
cp -a /etc/docker/daemon.json "${STAGING}/etc/" 2>/dev/null || true
cp -a /etc/systemd/journald.conf.d "${STAGING}/etc/" 2>/dev/null || true

# --- 2. Traefik config and ACME certs ---
log "Backing up Traefik..."
if [[ -d /opt/traefik ]]; then
    mkdir -p "${STAGING}/traefik"
    cp -a /opt/traefik/traefik.yml "${STAGING}/traefik/" 2>/dev/null || true
    cp -a /opt/traefik/docker-compose.yml "${STAGING}/traefik/" 2>/dev/null || true
    cp -a /opt/traefik/acme "${STAGING}/traefik/" 2>/dev/null || true
    cp -a /opt/traefik/dynamic "${STAGING}/traefik/" 2>/dev/null || true
fi

# --- 3. Docker volumes ---
log "Backing up Docker volumes..."
mkdir -p "${STAGING}/volumes"
for vol in $(docker volume ls -q 2>/dev/null); do
    log "  Volume: ${vol}"
    docker run --rm \
        -v "${vol}:/source:ro" \
        -v "${STAGING}/volumes:/backup" \
        alpine tar czf "/backup/${vol}.tar.gz" -C /source . 2>/dev/null || \
        log "  WARNING: Failed to backup volume ${vol}"
done

# --- 4. Create final archive ---
log "Creating archive..."
tar czf "${ARCHIVE}.tar.gz" -C "$STAGING" .
log "Archive created: ${ARCHIVE}.tar.gz ($(du -h "${ARCHIVE}.tar.gz" | cut -f1))"

# --- 5. Cleanup old backups ---
log "Removing backups older than ${RETENTION_DAYS} days..."
find "$BACKUP_DIR" -name "backup-*.tar.gz" -mtime "+${RETENTION_DAYS}" -delete

log "Backup complete."

# --- Offsite hook (uncomment and configure) ---
# To sync backups offsite, uncomment one of:
# rclone sync "$BACKUP_DIR" remote:backups/
# rsync -az "$BACKUP_DIR/" user@remote:/backups/
BACKUPSCRIPT

    chmod +x "$BACKUP_SCRIPT"
else
    log_info "[DRY RUN] Would generate backup script at ${BACKUP_SCRIPT}"
fi

log_ok "Backup script created at ${BACKUP_SCRIPT}."

# ---------------------------------------------------------------------------
# Install cron job
# ---------------------------------------------------------------------------
log_info "Installing cron job for daily backups..."

CRON_ENTRY="${BACKUP_CRON_TIME} root ${BACKUP_SCRIPT} >> /var/log/apps/backup.log 2>&1"

if [[ "$DRY_RUN" != "true" ]]; then
    # Write to /etc/cron.d/ for system-level cron (doesn't require crontab -e)
    echo "$CRON_ENTRY" > /etc/cron.d/server-backup
    chmod 644 /etc/cron.d/server-backup
else
    log_info "[DRY RUN] Would install cron: ${CRON_ENTRY}"
fi

log_ok "Backup cron installed: ${BACKUP_CRON_TIME}"

log_ok "Backup setup complete."
log_info "Manual run: sudo ${BACKUP_SCRIPT}"
log_info "Backups stored in: ${BACKUP_DATA_DIR}"
log_info "Retention: ${BACKUP_RETENTION_DAYS} days"
